name: Compile

on: [push | pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3
      - uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle Build
        run: ./gradlew build
